### PR TITLE
added message id to sendresponse

### PR DESCRIPTION
**Pull request by dominikheeb**
This would allow tracking of a mail message.
https://www.mailgun.com/blog/tracking-replies-in-mailgun-or-any-other-email

### CODE REVIEW

**Comment by Sakuto** [comment]
Not sure that modifying the global model just for one provider is a good idea.
That would be an useless property for every other provider.

**Comment by bjcull** [comment]
I'll have to have a think about this one. I think there's scope for each provider to return *something*, but I'm not sure how that should work yet. Bare with me.

**Comment by Sakuto** [comment]
Since `SendResponse` also have a generic form, something like: `SendResponse<MailgunResponse>` would allow you to retrieve these two parameters (Id, Message).

And without any modification to the current Model :)

**Comment by dominikheeb** [comment]
@Sakuto thx for the suggestion i will look if this is working for me.
But still i think you should think about implementing a way to get the message id, since it's a standard mail feature and not specific to Mailgun
https://tools.ietf.org/html/rfc2822#section-3.6.4
The rfc says as far as i can see that every message should have a message id and therefore all senders should also be able to implement this

**Comment by dominikheeb** [comment]
@Sakuto when i understand you right, i would need to change the code anyway to implement the SendResponse<MailgunResponse> answer.

To somehow sneek in the response in the data property of the SendResponse. Doesn't look as a nice design for me.

I mean for example how do you handle a reply on a mail you recieved from mailgun. There is also a feature missing allowing to set the "in-reply-to" header, which also uses the message id.

That's why i think it's important to implement message id in the library, since it's a basic function as the rfc standard says: https://tools.ietf.org/html/rfc2822#section-3.6.4

For that an update in the model would be needed and the other senders should also implement this functionality.

**Comment by Nixon-Joseph** [comment]
Any ideas on when/if this will be pulled into the prod branch? We are implementing a new MailGun system, and need the Id from the send response.

**Comment by dominikheeb** [comment]
@Nixon-Joseph as it looks they are not willing to take it into the branch.
It would be a great improvement to get back the message-id

**Comment by olibanjoli** [comment]
waiting eagerly for the nuget release 👍

**Pull request merged**
