### PR TITLE
Bugfix/mailgun async misuse

### PR DESCRIPTION
**Pull request by olibanjoli**
async await is not properly used in MailgunSender.

You should use ConfigureAwait(false) otherwise applications get locked up for example in IIS when calling MailgunSender.Send().

I fixed this issue in commit 79e5ac4.

More infos on this topic:
- https://stackoverflow.com/questions/10343632/httpclient-getasync-never-returns-when-using-await-async
- http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

Looking forward for a new nuget release containing this bugfix :)

### CODE REVIEW

**Comment by lukencode** [comment]
@bjcull you are using the Mailgun sender in prod? Mind taking a look?

**Comment by olibanjoli** [comment]
Why are you waiting so long to integrate this PR? Your library is essentially not usable in many scenarios since it locks up itself. Also reproducing the issue and see the fix working is pretty easy.

Looking forward to a new nuget release :).

**Comment by bjcull** [comment]
If you use await properly it's fine, though this is a definite improvement to catch people that don't.

Haven't gone through the finer details but will over coming days. Should be a new package by next weekend.

**Comment by olibanjoli** [comment]
> If you use await properly it's fine

Not sure what you mean @bjcull . The await is used improperly in the library itself and not accessible from outside. So there is no way from the outside to fix the issue. Hence my fix.

**Comment by bjcull** [comment]
Pushed to nuget in 2.5.1

**Pull request merged**
