### PR TITLE
Added support for Inline images for MailGun 

### PR DESCRIPTION
**Pull request by dapug**
Added support to designate an attachment as "inline" so that providers (such as MailGun) can do the right thing. Inline images typically render in the email body instead of showing as a file attachment. Depending on the email client, it means it will not render a "download" option for the attached image.

Note: the image used in the MailGun Test project here is a screenshot of the Raspberry Pi logo. Any image would do.

### CODE REVIEW

**Comment by mxmissile** [comment]
I like this, But does it have to be Sender specific? Couldn't it be added to Core?

**Comment by dapug** [comment]
Technically the inline option was added to core but not implemented in SMTP, and as for SendGrid, I am not familiar with their implementation in order to add it there.

**Comment by bjcull** [comment]
Resolves #74, partially solves #73.

**Comment by bjcull** [comment]
Tested and approved. Thanks for the effort @dapug :)

**Pull request merged**
