### PR TITLE
#82: Add Layout and ViewBag support for RazorRenderer

### PR DESCRIPTION
**Pull request by vanthoainguyen**

### CODE REVIEW

**Comment by lukencode** [comment]
Hi @vanthoainguyen. Can this work when using embedded resources rather than files on disk?

**Comment by vanthoainguyen** [comment]
I'll write some tests to see

**Comment by vanthoainguyen** [comment]
Beause of RazorLightEngineBuilder, it either use FilesystemProject or EmbeddedResourcesProject but not both.

I added another extension methods to FluentEmailRazorBuilderExtensions to allow developers to choose the type of RazorRenderer

2 unit tests also added to show how to use project layout , embedded layout with ViewBag

**Comment by lukencode** [comment]
Looks good. My suggestions are:

- Include a parameterless constructor for RazorRenderer that works as the previous version did
- Include a FluentEmailRazorBuilderExtensions method that works without providing a base directory / type
- Rename IHaveViewBag to something like IViewBagModel

**Comment by vanthoainguyen** [comment]
Done, also add an extension method to allow pass in RazorLightProject

**Comment by rafalschmidt97** [comment]
What's preventing this PR from being merged?

**Comment by dotnetshadow** [comment]
Has there been any update on this?

**Comment by lukencode** [comment]
@dotnetshadow have you tried in the latest version? I recently merged a razor light update.

**Comment by dotnetshadow** [comment]
@lukencode Yeah I think the issue is that fluentemail doesn't actually support it yet, it's not calling the new overloaded method

**Pull request merged**
